# Generated by Django 5.1 on 2024-10-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='updated_at',
            new_name='modifyed_at',
        ),
    ]
