# Generated by Django 5.1 on 2024-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
