# Generated by Django 5.1 on 2024-10-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_control', '0002_alter_game_created_by_alter_gamecategory_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifyed_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('end', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_control.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifyed_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=255)),
                ('rate', models.FloatField(default=1)),
                ('bets', models.IntegerField(default=0)),
                ('multi', models.IntegerField(default=0)),
                ('possible_return', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_control.gamequestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
