# Generated by Django 5.1 on 2024-10-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_control', '0003_gamequestion_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='game_control.game'),
        ),
    ]
