# Generated by Django 5.1 on 2024-10-30 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_control', '0004_alter_gamequestion_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='game_control.gamequestion'),
        ),
    ]
